### ISSUE TITLE
Error when clearing localStorage

### ISSUE THREAD

**Issue by mrdimidium** [nanostores/persistent#11]
Hello. Thank you for the work you are doing, nanostores is a wonderful tool.

I ran into a problem. If localStorage is cleared, for example via localStorage.clear() or via `Clear site data` in devtools, there will be an unhandled exception on `nanostores/persistent/index.js:62`. An exception will occur in neighboring tabs that are subscribed to localstorage updates.

This is due to the fact that the key in StorageEvent is an optional field. For example, if a field has been deleted, read more about it in the specification: https://html.spec.whatwg.org/multipage/webstorage.html#storageevent.

From what I understand, we can assume that if the key is not presented, it means that the storage has been cleared.

![2021-10-18_10-40-56_screenshot](https://user-images.githubusercontent.com/24303010/137688703-e87d1ead-e6df-4f35-bc02-8226a6fbcad6.png).

**Comment by ai** [comment]
Released in 0.4.1.
