### ISSUE TITLE
persistentAtom only allows string values

### ISSUE THREAD

**Issue by dvaJi** [nanostores/persistent#15]
This example doesn't work in typescript

```
import { persistentAtom } from '@nanostores/persistent'

export const shoppingCart = persistentAtom<Product[]>('cart', [])
```

**Comment by ai** [comment]
Yeap, because your value should be compatible with `string`.

If you have non-string value, you need to pass `encode` and `decode` options to convert `string` from `localStorage` to your value.

How we can improve docs to make it clear?
