### ISSUE TITLE
Specify shape of persistent object in localStorage

### ISSUE THREAD

**Issue by joshuaiz** [nanostores/persistent#21]
Hello, I'm using `nanostores` with Astro and it is really great.

I'm trying to save a single shopping cart object like so:
```
{
    cartId: '',
    checkoutUrl: '',
    estimatedCost: '',
    lines: [],
}
```
and then I would like to update individual values by key but not as separate `localStorage` items (e.g. using `persistentMap`).

This is my store function:
```
export const cartData = persistentAtom(
    'cart',
    {},
    {
        encode(cartObj) {
            return JSON.stringify(cartObj)
        },
        decode(cartObj) {
            return JSON.parse(cartObj)
        },
    }
)
```

and this is my setter function:

```
let cartObj = {
    ...cartData,
    lines: cartLines,
}

cartData.set(cartObj)
```

...which ends up like this in `localStorage`:

```
active: true
events: {5: [null], 6: [null]}
lc: 3
lines: [{,…}]
0: {,…}
node: {id: "gid://shopify/CartLine/0b803e10620b87e86db2a58a229d973c111ssd?cart=03076ea7c508dcfad2b19a679ceb3e6e111",…}
id: "gid://shopify/CartLine/0b803e10620b87e86db2a58a229d973c?cart=03076ea7c508dcfad2b19a679ceb3e6e111"
merchandise: {product: {title: "Short Sleeve Let's Dance Dress_Double Trouble Puppies",…}}
quantity: 1
value: {lc: 3, value: {}, events: {5: [null], 6: [null]}, active: true,…}
active: true
cartId: "gid://shopify/Cart/03076ea7c508dcfad2b19a679ceb3e6e1xxx"
checkoutUrl: "https://xxxxx.com/cart/c/03076ea7c508dcfad2b19a679ceb3e6e1xxxx"
events: {5: [null], 6: [null]}
lc: 3
value: {}
```

^^ while all my values are there, where are the other keys like `events`, `value`, `lc`, coming from? 

Ultimately I just want a single object with all the cart data with the keys that I provide and then to be able to update that object without having each key as a separate `localStorage` item. Is that possible?

**Comment by ai** [comment]
Your code should work.

What is `which ends up like this in localStorage`? Can you give some example with expected output and real output?

**Comment by joshuaiz** [comment]
Hi @ai thanks for the reply.

The expected output would be something like this under the `cart` key:
```
{
    cartId: 'gid://shopify/Cart/03076ea7c508dcfad2b19a679ceb3e6e1xxx',
    checkoutUrl: 'https://xxxxx.com/cart/c/03076ea7c508dcfad2b19a679ceb3e6e1xxxx',
    estimatedCost: '24.00',
    lines: [// cart lines array],
}
```
But instead I get what I posted above:

![CleanShot 2022-07-22 at 11 42 09](https://user-images.githubusercontent.com/1096738/180503440-c5431bbd-157d-41bc-9499-cb0b2ffb017f.png)

^^ that has all my data but a bunch of extra key/value pairs that I don't need like `lc`, `events`, etc. And it puts my object values under a `value` key which I don't need/want.

For simplicity, I'd just like the object I have above so I can reference like so:

```
cartData.cartId
cartData.checkoutUrl
// etc.
```
Does that make sense?

**Comment by ai** [comment]
Here is a  fix:

```diff
let cartObj = {
-    ...cartData,
-    ...cartData.get(),
    lines: cartLines,
}

cartData.set(cartObj)
```

**Comment by joshuaiz** [comment]
Boom! That did it.

Thanks so much.
