### ISSUE TITLE
persistentAtom does not set initial key-value pair in storage engine

### ISSUE THREAD

**Issue by vxncetxn** [nanostores/persistent#23]
### Describe the bug

`persistentAtom` does not correctly set initial key-value pair in storage engine.

### Your Example Website or App

[Minimal reproduction](https://stackblitz.com/edit/react-tjr44j)

### Steps to Reproduce the Bug or Issue

1. Open [Minimal reproduction](https://stackblitz.com/edit/react-tjr44j)
2. Observe that the key-value pair of `testItem`-`testValue` that was provided on creation in `store.js` is not properly set in `localStorage`. The runtime value also changes to `undefined`.
3. Observe that key-value pair is only correctly set after an action (accessed in example by button `onClick`).

**Comment by ai** [comment]
Thanks for well-formed issue and fix.

The fix was released in 0.6.1.
