### ISSUE TITLE
Question: custom persistent storage per persistentAtom

### ISSUE THREAD

**Issue by gor918** [nanostores/persistent#27]
How can I change my persistent storage only for one persistentAtom?

As a result of changing persistent storage to sessionStorage, all my localStorage values have been moved to sessionStorage, how can I avoid that? Thanks

**Comment by ai** [comment]
There is no API right now.

Do you want to send PR with add an option in atom constructor?

**Comment by gor918** [comment]
I do not have a solution for how to implement that, but if I find one I will create a PR :)
 Thanks for your quick reply :)
