### ISSUE TITLE
TypeError when using template string literal types in persistentMap generic

### ISSUE THREAD

**Issue by Mitsunee** [nanostores/persistent#28]
I'm currently working on migrating an existing codebase to typescript and would like to narrow the types of persistentMap using template string literal types, but am getting the following type error

![Screenshot_20221114_121542](https://user-images.githubusercontent.com/19474909/201646771-662d48e4-1646-4080-bed1-6e748f3f3360.png)

Note that it *works* anyways in the computed store below (that I haven't given stricter types yet, only checked that all props get their types from the interface).

**Comment by ai** [comment]
Very strange. But TS could be tricky sometimes.

Just `key: string` or `key: 'one' | 'two'` should works. Here is an example of type tests: https://github.com/nanostores/persistent/blob/main/test/types.ts#L19-L22

1. Can you simplify use case and pot a code example as a text to reproduce?
2. Could you replace `interface` to `type`? Sometimes it helps in TS for strange bugs.

**Comment by Mitsunee** [comment]
I was using `interface SettingsStored extends Partial<Record<string, string>>` as a workaround for a bit, but `type` works even better as it rejects properties that aren't in the type, problem solved 👍🏻 

Guess this is just typescript being weird as always. Here's a smaller reproduction:

```ts
import { persistentMap } from "@nanostores/persistent";
import { computed } from "nanostores";

type SpecificNumbers = 10 | 20 | 50;

interface SettingsStored {
  aNumber: `${number}`;
  specificNumbers: `${SpecificNumbers}`;
  aBoolean: `${boolean}`
  anyString: string;
}

const map = persistentMap<SettingsStored>("test:", {
  aNumber: "1",
  specificNumbers: "10",
  aBoolean: "false",
  anyString: "hello nanostores"
});

const computedStore = computed(map, store => ({
  aNumber: Number(store.aNumber),
  specificNumbers: Number(store.specificNumbers) as SpecificNumbers,
  aBoolean: store.aBoolean === "true",
  anyString: store.anyString
}))
```

This reproduces the type error in my original post. Changing Line 6 to either `interface SettingsStored extends Partial<Record<string, string>> {` or `type SettingsStore = {` fixes the error.

**Comment by ai** [comment]
The second type is used for the case when you define custom encoder/decoder. Seems like it is not your case, am I right?
