### ISSUE TITLE
[FEATURE] make encode and decode aync?

### ISSUE THREAD

**Issue by Alii-isk** [nanostores/persistent#29]
hi, thank for the amazing nanostores
i have a condition where i need to await an async function to execute but both encode and decode functions do no take asyc function

**Comment by ai** [comment]
What is use case? Why these functions are async?

**Comment by Alii-isk** [comment]
`
    const cover = await fileToBase64(values.cover);
    return JSON.stringify({ ...values, cover });
`

**Comment by ai** [comment]
Got it. Unfortunately, I can’t add it. But there is a better way.

Having async serialization will lead to many painful edge cases. Covering them will increase code complexity a lot.

But there is a better way to do what you want. The main problem with your approach, that you are moving business logic to encode/decode. Encode/decode functions should be just a simple filters (like `JSON.stringify`), not programs to read files, etc.

If you need a problem, you need to create another smart store, which will hide this complexity inside.

I recommend you creating a custom Nano Stores store, which will read data from `localStorage`, convert and save. It is not complex (just check this store source code, it is simple). It will be easier for you to write a straightforward store, than making a complex tower from many other stores.

**Comment by ai** [comment]
If you explain me your use case, I can explain how to write this custom store.

**Comment by Alii-isk** [comment]
> I recommend you creating a custom Nano Stores store, which will read data from localStorage,

that exactly what i did 😊

> If you explain me your use case, I can explain how to write this custom store.
its ok no i already made the logic i was just wondering why those function aren't asyc, now i know😊.

thank you so much, i only know about nanostores a week ago and i am really loving it ,very powerful with tiny buddle size
also thanks for nanoid 🥰🫡
