### ISSUE TITLE
Feature Request: Introduction of Session Storage

### ISSUE THREAD

**Issue by cauboy** [nanostores/persistent#42]
Is there a plan to also introduce sessionStorage in addition to localStorage for data persistence?

**Comment by ai** [comment]
What will be benefits of using sessionStorage in contrast with simple atom?

Am I right that sessionStorage is not shared between tabs?

**Comment by cauboy** [comment]
The benefit in contrast with simple atom would be that the session storage persists data when the user refreshes the page.

**Comment by ai** [comment]
Yes, just use different engine. I think we should not add it to the core since use case is rare (I think so, but people can change my opinion)

**Comment by blikblum** [comment]
I have an medical appointment booking app that i want to keep the data in current browser session only.

A sessionStorage fits my use case and i was expecting to be builtin
