### ISSUE TITLE
persistentAtom serialization using TypeScript

### ISSUE THREAD

**Issue by wpplumber** [nanostores/persistent#43]
Welcome, Thank you for this useful plugin.

I'm trying to create an object for a basket object using TS but it is not serialized is there a function or setup I'm missing?

```
interface Cart {
  zipCode: string
  isValidZip: boolean
  deliverySlots: string[]
  selectedSlot: string
  orders: Basket[]
  activeOrder: Basket | null
}

const initialCart: Cart = {
  zipCode: '',
  isValidZip: false,
  deliverySlots: [],
  selectedSlot: '',
  orders: [],
  activeOrder: null
}

export const basketStore = persistentAtom<Cart>('my_basket_', initialCart)
```

The key value on the browser local storage shows: `[object Object]` !

**Comment by wpplumber** [comment]
In case I use the `persistentMap` works ok!

**Comment by ai** [comment]
https://github.com/nanostores/persistent#value-encoding
