### ISSUE TITLE
Trouble switching from map to persistentMap

### ISSUE THREAD

**Issue by jacklenox** [nanostores/persistent#45]
I'm working on a shopping cart integration on an Astro site, and have everything working nicely after following the tutorial [here](https://github.com/withastro/astro/tree/main/examples/with-nanostores). However, I'm running into problems when trying to switch out the standard `map` for a `persistentMap`.

As per the tutorial, my nanostore code looks like this, and works great:

```ts
import { atom, map } from 'nanostores';

export const isCartOpen = atom(false);

export type CartItem = {
	id: string;
	name: string;
	imageSrc: string;
	quantity: number;
};

export type CartItemDisplayInfo = Pick<CartItem, 'id' | 'name' | 'imageSrc'>;

export const cartItems = map<Record<string, CartItem>>({});

export function addCartItem({ id, name, imageSrc }: CartItem) {
	const existingEntry = cartItems.get()[id];
	if (existingEntry) {
		cartItems.setKey(id, {
			...existingEntry,
			quantity: existingEntry.quantity + 1,
		});
	} else {
		cartItems.setKey(id, {
			id,
			name,
			imageSrc,
			quantity: 1,
		});
	}
}
```

However, things go awry when I switch my code to use `persistentMap` like so:

```ts
import { atom } from 'nanostores';
import { persistentMap } from '@nanostores/persistent';

export const isCartOpen = atom(false);

export type CartItem = {
	id: string;
	name: string;
	imageSrc: string;
	quantity: number;
};

export type CartItemDisplayInfo = Pick<CartItem, 'id' | 'name' | 'imageSrc'>;

export const cartItems = persistentMap<Record<string, CartItem>>({});

export function addCartItem({ id, name, imageSrc }: CartItem) {
	const existingEntry = cartItems.get()[id];
	if (existingEntry) {
		cartItems.setKey(id, {
			...existingEntry,
			quantity: existingEntry.quantity + 1,
		});
	} else {
		cartItems.setKey(id, {
			id,
			name,
			imageSrc,
			quantity: 1,
		});
	}
}
```

The cart steadily turns into a mess of objects nesting inside objects, and I get the following error after I declare the `persistentMap`:

```
Type 'Record<string, CartItem>' does not satisfy the constraint 'Record<string, string | undefined>'. 'string' index signatures are incompatible. Type 'CartItem' is not assignable to type 'string'.
```

I'm guessing the issue here is I need a string which will name the overall record in local storage, but I can't work out the correct way of doing this.

**Comment by ai** [comment]
You need to pass `encode` and `decode` options to `persistentMap` (see examples in main `README.md`)

**Comment by jacklenox** [comment]
Thanks, although I've tried that and I'm still having the same problem.

**Comment by ai** [comment]
Show the code which you tried and the error with this code

**Comment by jacklenox** [comment]
It's the same as the above but with the encode and decode options:

```ts
import { atom } from 'nanostores';
import { persistentMap } from '@nanostores/persistent';

export const isCartOpen = atom(false);

export type CartItem = {
	id: string;
	name: string;
	imageSrc: string;
	quantity: number;
};

export type CartItemDisplayInfo = Pick<CartItem, 'id' | 'name' | 'imageSrc'>;

export const cartItems = persistentMap<Record<string, CartItem>>({
	encode: JSON.stringify,
	decode: JSON.parse,
});

export function addCartItem({ id, name, imageSrc }: CartItem) {
	const existingEntry = cartItems.get()[id];
	if (existingEntry) {
		cartItems.setKey(id, {
			...existingEntry,
			quantity: existingEntry.quantity + 1,
		});
	} else {
		cartItems.setKey(id, {
			id,
			name,
			imageSrc,
			quantity: 1,
		});
	}
}
```

**Comment by ai** [comment]
You use a wrong API of `persistentMap()`. It is `persistentMap(defaultValue, opts)`

**Comment by jacklenox** [comment]
OK thanks. I still don't entirely understand this because it seems I need to pass three parameters to `persistentMap()`, a label, a default value and options. In case anyone stumbles upon this in future, things seem to be working as intended with the following change:

```ts
export const cartItems = persistentMap<Record<string, CartItem>>('cart:', {}, {
	encode: JSON.stringify,
	decode: JSON.parse,
});
```

**Comment by Joeao** [comment]
Recreating the code in [the docs ](https://github.com/nanostores/persistent?tab=readme-ov-file#map-store)shows this error message until the third parameter is added, as in the example provided by @jacklenox
![image](https://github.com/user-attachments/assets/a2030f71-9f29-4481-bd4a-b2c637d7d0ad)
![image](https://github.com/user-attachments/assets/a03eb647-f4b0-4948-a4db-f4f9964496e6)
