### ISSUE TITLE
QuotaExceededError: The quota has been exceeded on iOS

### ISSUE THREAD

**Issue by joshuaiz** [nanostores/persistent#52]
Hello,

Using nanostores + persistent to store cart data for an e-commerce website and intermittently seeing the `QuotaExceededError: The quota has been exceeded.` error on iOS + Safari.

In our case, this seemingly prevents writing to the `cart` store and people are unable to add products to their cart which is not good.

My questions are:

1. What causes this issue? Is it a space limitation? Or too many requests to the store? Something else?
2. How can I fix it?

There was a previous issue https://github.com/nanostores/persistent/issues/7 that I'm not sure is related but that is listed as `fixed`. 

Any insight here would be appreciated. Thanks!

**Comment by ai** [comment]
There are 2 reasons: 

1. You store > 1-10 MB data there. Local Storage can store only small amount of data. 
2. People are using private mode which disable Local Storage and in old versions Safari uses this error to tell about it. 

How much data is stored and what is Safari version?

**Comment by joshuaiz** [comment]
Thanks @ai - I found the culprit which is another process storing large array of JSON objects so that was exceeding the 5 or 10MB allotted.

Going to find another option for that data and for now this is resolved.
