### ISSUE TITLE
How to persist a deepMap?

### ISSUE THREAD

**Issue by Dav3rs** [nanostores/persistent#53]

**Comment by ai** [comment]
`localStorage` is flat key-value storage, so there is not really native way to use it as deep map.

Why `atom({ some: { inside: true } })` with an object doesn’t feet you, and you need separated key for every nested element?

**Comment by Dav3rs** [comment]
Just missing the ergonomics of doing
```ts
$deepMap.setKey("driversData[0].name", "foo");
$deepMap.setKey("driversData[0].age", 34);
```

**Comment by ai** [comment]
Just create a helper using `deepMap` code https://github.com/nanostores/nanostores/blob/main/deep-map/index.js#L11 and use it for `persistentAtom`

**Comment by YadBro** [comment]
> Just create a helper using `deepMap` code https://github.com/nanostores/nanostores/blob/main/deep-map/index.js#L11 and use it for `persistentAtom`

Could you give me an example, please?
