### ISSUE TITLE
useStore(persistentStore) is not universal in react

### ISSUE THREAD

**Issue by droganov** [nanostores/persistent#6]
The case — we want to use `useStore(persistentStore)` with next.js

The problem:
1. SSR goes well and results in `initialState` returned by the hook
2. Client render goes well and results in `lastState` returned by the hook
3. Hydration goes not so good and results in SSR/Client trees mismatch

Ideally we want `useStore` to output `initialState` unless it mounts.

I made a custom hook that solves the problem locally, but think it worth solving it on a library level

```ts
export const useClientStore = <S>(
  store: ReadableStore<S>,
  defaultState: S
): S => {
  const isMounted = useIsMounted()
  const state = useStore(store)
  return isMounted ? state : defaultState
}
```

**Comment by ai** [comment]
Our current idea is to handle it on store level rather than changing the components (components should be dumb).

I will add example to Persistent Store to explain it.

**Comment by droganov** [comment]
Just an idea, if we separate store in the storage layers, we could use store initializer to bridge store and localstorage

```ts
const backend = createPersistentBackend(name, { encode, decode })
const store = createStore(() => {
  const unbridge = bridge(store, backend)
  return unbridge
})

```

**Comment by ai** [comment]
I added a small note about SSR to docs 19d23ff

> Just an idea, if we separate store and storage layers, we could use store initializer to bridge store and localstorage

It looks very complicated. But if you want to hide SSR complexity, you can use custom engine.

**Comment by droganov** [comment]
There is must be a confusion.
[19d23ff](https://github.com/nanostores/persistent/commit/19d23ff4beb712638d4415bd28524712685abf13) would only work for registered users.

For the guest case we have to deal with the store init somehow

**Comment by ai** [comment]
> For the guest case we have to deal with the store init somehow

Yeap, you can use locale from client’s HTTP header.

I am not sure that we should show this complexity in the example.

**Comment by droganov** [comment]
Actually [19d23ff](https://github.com/nanostores/persistent/commit/19d23ff4beb712638d4415bd28524712685abf13) should not be advertised, because it's not thread-safe.

If we use renderToNodeStream or suspense we may hit into troubles.

I think we should not use setters during render

**Comment by ai** [comment]
Multi-user environment requires an entirely different architecture in your front-end.

I do not see a good solution if you are sharing context between users, since `useStore` is just a hack. You can leak sensitive data since you are storing it in the single context.

Why not using a different context for each users to be sure that data is isolated?

**Comment by droganov** [comment]
Well, that's what I'm saying about the architecture :-)

I think I'm OK on b/e :

1. I don't have b/e sessions — all users get the same initial state, no side effects in render though no collisions
2. I separate concerns of state management and data loading

The original problem is that the default state (coming from the back-end) doesn't match the state from the local storage of a particular user. And this creates a hydration warning in React when DOM threes are not equal. That's not a catastrophe, but I'm thinking of avoiding both the React warning and the content flickering.
